services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=eter_netcafe_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
